Autorization
BubuntuClu/trainsrep pull request #6
Opened 2016-12-07 18:42 UTC by BubuntuClu

2016-12-08 09:36 UTC, vkurennov requested changes

2016-12-08 09:36 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    if current_user.admin?
Лучше разделить на 2 контроллера: один для пользователя, другой для админа. Так у тебя (и у других разработчиков) всегда будет четкое понимание, где лежат контроллеры для админки, а где пользовательские.

2016-12-08 09:36 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    @ticket = current_user.tickets.new(ticket_params)
В случае с админом он будет создавать билет для самого себя, что не имеет особого смысла. Сделай так,чтобы админ мог создавать билеты для любого зарегестрированного пользователя (выбрать его из списка). Это также лучше сделать в отдельном контроллере

2016-12-08 09:36 UTC, vkurennov commented on app/controllers/tickets_controller.rb
>    before_action :hidden_params, only: [:new]
И что это за метод? Где он определен? Что-то я не нашел его.

2016-12-08 09:36 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    current_user.tickets.find(params[:id]).destroy
В этом случае админ может удалять только свои билеты, что опять же смысла не имеет

2016-12-08 09:36 UTC, vkurennov commented on config/routes.rb
> +    resources :tickets
ресурс для билетов в админке есть, а контроллера нет

2016-12-08 16:19 UTC, BubuntuClu commented
Что-то не понравилось мне дублирование в ticket_controller'ах и во view'аха. Не придумал как это можно красиво сделать.

2016-12-09 12:42 UTC, vkurennov approved these changes

2016-12-09 12:42 UTC, vkurennov commented on app/controllers/admin/tickets_controller.rb
> +    Ticket.find(params[:id]).destroy
У тебя же есть метод set_ticket

2016-12-09 12:42 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    @ticket = current_user.tickets.new(ticket_params)
Нашел :-)

2016-12-09 15:30 UTC, merged